#! /bin/bash

npm run build

aws s3 rm --region us-east-1 --profile terraform --recursive s3://suziespals.co.uk/

aws s3 cp --region us-east-1 --profile terraform --recursive ./dist/ s3://suziespals.co.uk/

